# Generated by Django 5.1.3 on 2024-11-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_de_licence', models.CharField(max_length=50, unique=True)),
                ('horaires_de_travail', models.JSONField(blank=True, null=True)),
                ('evaluation', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin')], max_length=10)),
                ('numero_de_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_de_debut', models.TimeField()),
                ('heure_de_fin', models.TimeField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='goodDoctor.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('en attente', 'En attente')], default='en attente', max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_medecin', to='goodDoctor.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_patient', to='goodDoctor.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('medicaments', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('date_de_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateurs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_medical', to='goodDoctor.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('rappel_rdv', 'Rappel Rendez-vous'), ('rappel_medicaments', 'Rappel Médicaments')], max_length=20)),
                ('date_heure_envoi', models.DateTimeField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('utilisateurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='goodDoctor.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('lu', 'Lu'), ('non lu', 'Non lu')], default='non lu', max_length=10)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='goodDoctor.utilisateurs')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='goodDoctor.utilisateurs')),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='utilisateurs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='goodDoctor.utilisateurs'),
        ),
        migrations.CreateModel(
            name='HistoriqueAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('type_acces', models.CharField(max_length=100)),
                ('ip_adresse', models.GenericIPAddressField()),
                ('utilisateurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_acces', to='goodDoctor.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_medecin', to='goodDoctor.medecin')),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='goodDoctor.rendezvous')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_patient', to='goodDoctor.utilisateurs')),
            ],
        ),
    ]
