# Generated by Django 5.1.3 on 2025-01-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('goodDoctor', '0002_alter_utilisateurs_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='date_de_naissance',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='numero_de_telephone',
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$KUFUiDqhj2nCV6krJgCYyy$tGtl2b/cfpSuJ3ONwnABtqtVQ9NKVP7+P3MTJswDrEw=', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
