# Generated by Django 5.1.3 on 2025-01-06 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodDoctor', '0003_remove_utilisateurs_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('medecin_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_crees', to='goodDoctor.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_medical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
