# Generated by Django 5.1.3 on 2025-01-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodDoctor', '0004_historiquemedical'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
